import './globals.css';

import Navbar from '@/components/Navbar';

export const metadata = {
	title: 'Catholic Prayer Blog Next JS 13',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<main className='app'>
					<Navbar />
					{children}
				</main>
			</body>
		</html>
	);
}
